import Link from "next/link";
import { connection } from "next/server";
import { requireDashboardSession } from "@/lib/auth/authorization";
import { getInventoryFeed } from "@/lib/inventory/live-data";

export default async function AttentionPage() {
  await requireDashboardSession(); await connection(); const feed = await getInventoryFeed();
  const items = feed.items.filter((item) => item.status === "low-stock" || item.status === "out-of-stock").sort((a,b)=>a.today-b.today);
  return <div className="space-y-6"><div><p className="text-xs font-medium text-emerald-700">Inventory action queue</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Products requiring attention</h1><p className="mt-1 text-sm text-slate-500">Low and out-of-stock variants, using product-specific thresholds where configured.</p></div><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50 text-slate-400"><tr><th className="px-5 py-3">Product</th><th>Variant / SKU</th><th>Location</th><th>Lifecycle</th><th className="text-right">Stock</th><th>Status</th><th/></tr></thead><tbody>{items.map((item)=><tr key={`${item.inventoryItemId}-${item.locationId}`} className="border-t border-slate-100"><td className="px-5 py-3 font-semibold text-slate-800">{item.productTitle}</td><td>{item.variantTitle}<span className="block text-slate-400">{item.sku??"No SKU"}</span></td><td>{item.locationName}</td><td className="capitalize">{(item.productStatus??"unknown").toLowerCase()}</td><td className={`text-right font-bold ${item.today<=0?"text-red-600":"text-amber-700"}`}>{item.today}</td><td className="capitalize">{item.status.replaceAll("-"," ")}</td><td className="px-4"><Link className="text-emerald-700" href={`/inventory/${encodeURIComponent(item.inventoryItemId)}`}>Details</Link></td></tr>)}</tbody></table>{!items.length?<p className="p-8 text-center text-sm text-slate-500">No products currently require attention.</p>:null}</div></div>;
}
