"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Icon } from "@/components/ui/icon";
import type { PhysicalInventoryProduct } from "@/types/physical-inventory";
import type { InventoryStatus } from "@/types/inventory";
import { StatusBadge } from "./status-badge";

const PAGE_SIZE = 15;

export function PhysicalInventoryTable({ products }: { products: PhysicalInventoryProduct[] }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"all" | InventoryStatus>("all");
  const [sortByStock, setSortByStock] = useState(false);
  const [page, setPage] = useState(1);
  const filtered = useMemo(() => products.filter((product) => {
    const matchesQuery = `${product.displayName} ${product.sku}`.toLowerCase().includes(query.trim().toLowerCase());
    return matchesQuery && (status === "all" || product.status === status);
  }).sort((left, right) => sortByStock ? right.actual - left.actual || left.displayName.localeCompare(right.displayName) : left.displayName.localeCompare(right.displayName)), [products, query, status, sortByStock]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  function resetPage() { setPage(1); }
  return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white">
    <div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 flex-1 flex-wrap gap-3"><div className="relative min-w-[220px] flex-1"><Icon name="search" className="absolute left-3 top-2.5 size-4 text-slate-400"/><input value={query} onChange={(event) => { setQuery(event.target.value); resetPage(); }} className="h-9 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-xs outline-none focus:border-emerald-700" placeholder="Search product or SKU..."/></div><select value={status} onChange={(event) => { setStatus(event.target.value as typeof status); resetPage(); }} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs text-slate-600"><option value="all">All stock statuses</option><option value="in-stock">In stock</option><option value="low-stock">Low stock</option><option value="out-of-stock">Out of stock</option></select></div><button type="button" onClick={() => setSortByStock((value) => !value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-600">{sortByStock ? "Sorted by stock" : "Sort by stock"}</button></div>
    <div className="border-b border-emerald-100 bg-emerald-50/60 px-5 py-3 text-xs leading-5 text-emerald-900"><strong>Physical product stock only.</strong> Counts are individual packets in the command-center database. Shopify packs, bundles, and combo listings are intentionally excluded from this screen.</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/70 text-[10px] uppercase tracking-wide text-slate-400"><th className="px-5 py-3 font-semibold">Product</th><th className="px-3 py-3">SKU</th><th className="px-3 py-3 text-right font-semibold">Actual packets</th><th className="px-3 py-3 text-right font-semibold">Online</th><th className="px-3 py-3 text-right font-semibold">Retail</th><th className="px-3 py-3 text-right font-semibold">Buffer</th><th className="px-3 py-3 text-right font-semibold">QC</th><th className="px-3 py-3">Stock health</th><th className="px-4 py-3"/></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((product) => <tr key={product.id} className="text-xs text-slate-600 hover:bg-slate-50/70"><td className="px-5 py-3.5"><p className="font-semibold text-slate-800">{product.displayName}</p><p className="mt-1 text-[10px] text-slate-400">{product.locations.join(", ")} · updated {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(new Date(product.updatedAt))}</p></td><td className="px-3 py-3.5 font-mono text-[11px] text-slate-500">{product.sku}</td><td className="px-3 py-3.5 text-right text-lg font-bold tabular-nums text-slate-950">{product.actual}<span className="mt-0.5 block text-[9px] font-normal uppercase tracking-wide text-slate-400">packets</span></td><td className="px-3 py-3.5 text-right font-bold tabular-nums text-emerald-700">{product.online}</td><td className="px-3 py-3.5 text-right font-bold tabular-nums text-blue-700">{product.retail}</td><td className="px-3 py-3.5 text-right font-bold tabular-nums text-amber-700">{product.buffer}</td><td className="px-3 py-3.5 text-right font-bold tabular-nums text-violet-700">{product.qc}</td><td className="px-3 py-3.5"><StatusBadge status={product.status}/></td><td className="px-4 py-3.5"><Link href={`/inventory/${product.id}`} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 font-bold text-emerald-700">View ledger <Icon name="chevron" className="size-4"/></Link></td></tr>)}</tbody></table></div>
    {!visible.length ? <div className="grid min-h-56 place-items-center text-center"><div><div className="mx-auto grid size-11 place-items-center rounded-full bg-slate-100"><Icon name="search" className="size-5 text-slate-400"/></div><p className="mt-3 text-sm font-semibold text-slate-700">No physical products found</p><p className="mt-1 text-xs text-slate-400">Only products with a warehouse-ledger balance appear here.</p></div></div> : <div className="flex items-center justify-between border-t border-slate-100 px-5 py-4"><p className="text-[11px] text-slate-400">Showing products {(page - 1) * PAGE_SIZE + 1}–{Math.min(page * PAGE_SIZE, filtered.length)} of {filtered.length}</p><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage((current) => current - 1)} className="rounded-md border border-slate-200 px-3 py-1.5 text-xs disabled:opacity-40">Previous</button><button disabled={page === pages} onClick={() => setPage((current) => current + 1)} className="rounded-md border border-slate-200 px-3 py-1.5 text-xs disabled:opacity-40">Next</button></div></div>}
  </section>;
}
