"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { SnapshotRun } from "@/types/operations";

export function SnapshotControls({ today, latestSnapshotDate, runs }: { today: string; latestSnapshotDate: string | null; runs: SnapshotRun[] }) {
  const router = useRouter(); const [busy, setBusy] = useState<"refresh" | "snapshot" | null>(null); const [message, setMessage] = useState("");
  async function snapshot() { setBusy("snapshot"); setMessage(""); const response = await fetch("/api/inventory/snapshot", { method: "POST" }); const body = await response.json(); setMessage(response.ok ? `Snapshot saved for ${body.snapshot.snapshotDate}.` : body.error ?? "Snapshot failed."); setBusy(null); if (response.ok) router.refresh(); }
  function refresh() { setBusy("refresh"); router.refresh(); setTimeout(() => setBusy(null), 700); }
  const lastSuccess = runs.find((run) => run.status === "success");
  return <section className={`rounded-xl border p-4 ${latestSnapshotDate === today ? "border-emerald-200 bg-emerald-50/60" : "border-amber-200 bg-amber-50/70"}`}>
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-semibold text-slate-800">Snapshot operations</p><p className="mt-1 text-xs text-slate-600">{latestSnapshotDate === today ? `Today’s snapshot is available (${today}).` : `Warning: the daily snapshot for ${today} is missing.`} {lastSuccess ? `Last successful run: ${new Date(lastSuccess.completedAt).toLocaleString("en-IN")}.` : "No successful execution is recorded yet."}</p>{message ? <p className="mt-1 text-xs font-medium text-emerald-700">{message}</p> : null}</div><div className="flex gap-2"><button onClick={refresh} disabled={Boolean(busy)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700">{busy === "refresh" ? "Refreshing…" : "Refresh live data"}</button><button onClick={snapshot} disabled={Boolean(busy)} className="rounded-lg bg-brand-primary px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy === "snapshot" ? "Creating…" : "Create snapshot"}</button></div></div>
    {runs.length ? <details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-slate-600">Recent cron and manual runs</summary><div className="mt-2 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-400"><tr><th className="py-2">Started</th><th>Source</th><th>Status</th><th>Snapshot</th><th>Message</th></tr></thead><tbody>{runs.slice(0, 8).map((run) => <tr key={run.id} className="border-t border-slate-200/70"><td className="py-2">{new Date(run.startedAt).toLocaleString("en-IN")}</td><td className="capitalize">{run.source}</td><td className={run.status === "success" ? "text-emerald-700" : "text-red-600"}>{run.status}</td><td>{run.snapshotDate ?? "—"}</td><td>{run.message}</td></tr>)}</tbody></table></div></details> : null}
  </section>;
}
