import Link from "next/link";
import { connection } from "next/server";
import { requireDashboardSession } from "@/lib/auth/authorization";
import { getCommandCenterView } from "@/services/command-center";
import type { CommandCenterDecision, CommandCenterHealth } from "@/types/command-center";

const integer = new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 });

export default async function Home() {
  await requireDashboardSession(); await connection();
  const view = await getCommandCenterView();
  return <div className="space-y-7">
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#2d725f]">Commerce + Warehouse</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-900">Decision Command Center</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Live Shopify stock and demand are connected. Warehouse allocation remains separated until its transactional source of truth is added.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800"><span className="size-2 rounded-full bg-emerald-500"/>Shopify {view.mode === "live" ? "connected" : view.mode === "snapshot" ? "snapshot fallback" : "unavailable"}</div></header>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Online stock" value={integer.format(view.onlineStock)} helper="Actual Shopify available" tone="green"/><UnavailableMetric label="Retail stock"/><UnavailableMetric label="Buffer stock"/><UnavailableMetric label="Total physical stock"/>
      <Metric label="Shopify units today" value={value(view.onlineUnitsToday)} helper="Current order quantities"/><Metric label="Shopify orders today" value={value(view.shopifyOrdersToday)} helper={view.salesError ? "Order access needs attention" : "Processed today"}/><Metric label="Average online demand" value={view.averageDailyOnlineUnits === null ? "—" : `${view.averageDailyOnlineUnits}/day`} helper="Recent 30-day run rate"/><Metric label="SKUs requiring attention" value={integer.format(view.lowStockSkus + view.outOfStockSkus)} helper={`${view.outOfStockSkus} out · ${view.lowStockSkus} low`} tone="amber"/>
    </section>

    <section className="grid gap-5 xl:grid-cols-[1.45fr_.8fr]">
      <div className="rounded-xl border border-slate-200 bg-white"><div className="flex items-start justify-between gap-4 border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-semibold text-slate-900">Decision required</h2><p className="mt-1 text-xs text-slate-500">Detect → explain → recommend. Execution stays disabled until safe warehouse balances exist.</p></div><Link href="/attention" className="shrink-0 text-xs font-semibold text-emerald-700">View all stock alerts</Link></div><div className="divide-y divide-slate-100">{view.decisions.map((decision) => <Decision key={decision.id} decision={decision}/>)}{!view.decisions.length ? <div className="p-8 text-center"><p className="text-sm font-semibold text-slate-700">No demand-based decision is urgent</p><p className="mt-1 text-xs text-slate-500">The queue will populate when stock cover falls below 10 days.</p></div> : null}</div></div>
      <div className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">SKU identity health</h2><div className="mt-5 grid grid-cols-2 gap-3"><MiniMetric label="Mapped rows" value={view.mappedSkus}/><MiniMetric label="Missing SKU" value={view.missingSkus} danger={view.missingSkus > 0}/></div><p className="mt-4 text-xs leading-5 text-slate-500">Shopify inventory-item SKU is primary, with variant SKU as fallback. Missing SKUs must be resolved before warehouse stock is imported.</p><Link href="/inventory" className="mt-4 inline-flex text-xs font-semibold text-emerald-700">Review inventory identities →</Link></section><section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Warehouse foundation required</p><h2 className="mt-2 text-sm font-semibold text-slate-900">Connect transactional inventory</h2><p className="mt-2 text-xs leading-5 text-slate-600">Retail, Buffer, physical totals, transfers, receiving and approvals are intentionally unavailable—not treated as zero. They require atomic balances, an immutable ledger and an integration outbox.</p></section></div>
    </section>
  </div>;
}

function value(number: number | null) { return number === null ? "—" : integer.format(number); }
function Metric({ label, value, helper, tone = "slate" }: { label: string; value: string; helper: string; tone?: "slate" | "green" | "amber" }) { const color = tone === "green" ? "text-emerald-700" : tone === "amber" ? "text-amber-700" : "text-slate-900"; return <div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-medium text-slate-500">{label}</p><p className={`mt-2 text-2xl font-semibold ${color}`}>{value}</p><p className="mt-1 text-[11px] text-slate-400">{helper}</p></div>; }
function UnavailableMetric({ label }: { label: string }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50/70 p-5"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-slate-400">Not connected</p><p className="mt-1 text-[11px] text-slate-400">Warehouse source required</p></div>; }
function MiniMetric({ label, value, danger = false }: { label: string; value: number; danger?: boolean }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-1 text-xl font-semibold ${danger ? "text-red-600" : "text-slate-800"}`}>{value}</p></div>; }

function Decision({ decision }: { decision: CommandCenterDecision }) { return <article className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><HealthBadge health={decision.health}/><span className="text-[11px] text-slate-400">{decision.sku ?? "Missing SKU"}</span></div><h3 className="mt-2 text-sm font-semibold text-slate-900">{decision.productTitle}</h3><p className="mt-1 text-xs text-slate-600">{decision.reason}</p><p className="mt-3 text-xs"><span className="font-semibold text-slate-800">Recommended:</span> <span className="text-slate-600">{decision.recommendation}</span></p></div><div className="grid shrink-0 grid-cols-3 gap-2 text-center"><DecisionNumber label="Online" value={decision.onlineStock}/><DecisionNumber label="Avg/day" value={decision.averageDailyUnits}/><DecisionNumber label="Cover" value={decision.daysCover === null ? "—" : `${decision.daysCover}d`}/></div></div><div className="mt-4 flex gap-2"><Link href={`/inventory/${encodeURIComponent(decision.inventoryItemId)}`} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700">Review product</Link><button disabled title="Warehouse balances are not connected" className="rounded-lg bg-slate-200 px-3 py-2 text-xs font-semibold text-slate-500">Approve transfer</button></div></article>; }
function DecisionNumber({ label, value }: { label: string; value: string | number }) { return <div className="min-w-16 rounded-lg bg-slate-50 px-2 py-2"><p className="text-[9px] uppercase text-slate-400">{label}</p><p className="mt-1 text-xs font-bold text-slate-800">{value}</p></div>; }
const healthStyles: Record<CommandCenterHealth, string> = { healthy: "bg-emerald-50 text-emerald-700", monitor: "bg-blue-50 text-blue-700", low: "bg-amber-50 text-amber-700", critical: "bg-orange-50 text-orange-700", urgent: "bg-red-50 text-red-700", "out-of-stock": "bg-slate-800 text-white" };
function HealthBadge({ health }: { health: CommandCenterHealth }) { return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase tracking-wide ${healthStyles[health]}`}>{health.replaceAll("-", " ")}</span>; }
