"use client";
import { useState } from "react";
import type { OperationsSettings } from "@/types/operations";

interface ProductOption { id: string; title: string }
export function OperationsSettingsForm({ initial, products }: { initial: OperationsSettings; products: ProductOption[] }) {
  const [settings, setSettings] = useState(initial); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  function numeric(field: "defaultLowStockThreshold" | "leadTimeDays" | "safetyStockDays" | "deadStockDays", value: string) { setSettings((current) => ({ ...current, [field]: Number(value) })); }
  async function save() { setSaving(true); setMessage(""); const response = await fetch("/api/operations/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const body = await response.json(); if (response.ok) { setSettings(body); setMessage("Settings saved."); } else setMessage(body.error ?? "Could not save settings."); setSaving(false); }
  return <div className="space-y-5"><section className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-2 xl:grid-cols-4">{([['defaultLowStockThreshold','Default low-stock threshold'],['leadTimeDays','Supplier lead time (days)'],['safetyStockDays','Safety stock (days)'],['deadStockDays','Dead-stock window (days)']] as const).map(([field,label]) => <label key={field} className="text-xs font-semibold text-slate-600">{label}<input type="number" min="0" value={settings[field]} onChange={(event) => numeric(field,event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/></label>)}</section>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-800">Alerts and defaults</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.hideUntrackedByDefault} onChange={(e)=>setSettings({...settings,hideUntrackedByDefault:e.target.checked})}/> Hide untracked variants</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.alerts.emailEnabled} onChange={(e)=>setSettings({...settings,alerts:{...settings.alerts,emailEnabled:e.target.checked}})}/> Daily email summary</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.alerts.whatsappEnabled} onChange={(e)=>setSettings({...settings,alerts:{...settings.alerts,whatsappEnabled:e.target.checked}})}/> Daily WhatsApp summary</label></div><p className="mt-3 text-xs text-slate-400">Enabled channels send after the successful 7:00 AM IST snapshot and require their server credentials.</p></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-800">Thresholds by product</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{products.map((product)=><label key={product.id} className="flex items-center justify-between gap-4 rounded-lg border border-slate-100 px-3 py-2 text-xs text-slate-700"><span>{product.title}</span><input aria-label={`${product.title} threshold`} type="number" min="0" placeholder={String(settings.defaultLowStockThreshold)} value={settings.productThresholds[product.id] ?? ""} onChange={(event)=>{const next={...settings.productThresholds}; if(event.target.value==="") delete next[product.id]; else next[product.id]=Number(event.target.value); setSettings({...settings,productThresholds:next});}} className="h-8 w-24 rounded-md border border-slate-200 px-2"/></label>)}</div></section>
    <div className="flex items-center gap-3"><button onClick={save} disabled={saving} className="rounded-lg bg-[#164c3d] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving…":"Save settings"}</button>{message?<p className="text-xs text-emerald-700">{message}</p>:null}</div></div>;
}
